sudo: false

os:
- linux
#- osx

addons:
  apt_packages:
    - pandoc

#cache:
#  directories:
#  - "$HOME/download/"
#  - "$HOME/install/"

env:
  #- PYTHON_VERSION=2.7
  #- PYTHON_VERSION=3.3
  #- PYTHON_VERSION=3.4
  - PYTHON_VERSION=3.5

before_install:
- wget https://github.com/mzwiessele/travis_scripts/raw/master/download_miniconda.sh
- wget https://github.com/mzwiessele/travis_scripts/raw/master/install_retry.sh
- source download_miniconda.sh
- echo $PATH

install:
- echo $PATH
- source install_retry.sh
- conda install --yes jupyter ipywidgets 
- pip install pypandoc

script:
  - sh run_notebooks.sh

