baseurl: /Issue1
port: 4001

files_url: https://github.com/MC-Notes/Issue1/blob/master/

# Permalinks
permalink: /:year/:month/:day/:title/

markdown: kramdown
markdown_ext: markdown,md
#pandoc:
#  extensions: 
#    - smart
#    - mathjax
    
encoding: utf-8

exclude:
  - Gemfile
  - Gemfile.lock
