#baseurl: https://github.com/MC-Notes/mc-notes.github.io
port: 4001

# Permalinks
permalink: /:year/:month/:day/:title/

markdown: kramdown
markdown_ext: markdown,md
#pandoc:
#  extensions: 
#    - smart
#    - mathjax
    
encoding: utf-8

exclude:
  - Gemfile
  - Gemfile.lock
